services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    volumes:
      - .:/code
